// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyOfA4G72t556GfEf3kBWNF6z2rJ5OjKo',
    appId: '1:690601335117:web:f785bd8318393864173f04',
    messagingSenderId: '690601335117',
    projectId: 'mad-lab-project-3008f',
    authDomain: 'mad-lab-project-3008f.firebaseapp.com',
    databaseURL: 'https://mad-lab-project-3008f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mad-lab-project-3008f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6bEPWJOismgS1g7FXo4DZuHQOqb6AXBI',
    appId: '1:690601335117:android:c903506b9a84f299173f04',
    messagingSenderId: '690601335117',
    projectId: 'mad-lab-project-3008f',
    databaseURL: 'https://mad-lab-project-3008f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mad-lab-project-3008f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3JxBtyR-EFgaFrbRxr-gKJSDjqhJ8d8I',
    appId: '1:690601335117:ios:bfc4fd444302e380173f04',
    messagingSenderId: '690601335117',
    projectId: 'mad-lab-project-3008f',
    databaseURL: 'https://mad-lab-project-3008f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mad-lab-project-3008f.appspot.com',
    iosClientId: '690601335117-tptv5saanq3mnod5uc49jifeiq5q59rk.apps.googleusercontent.com',
    iosBundleId: 'com.siddharth.loginRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3JxBtyR-EFgaFrbRxr-gKJSDjqhJ8d8I',
    appId: '1:690601335117:ios:bfc4fd444302e380173f04',
    messagingSenderId: '690601335117',
    projectId: 'mad-lab-project-3008f',
    databaseURL: 'https://mad-lab-project-3008f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mad-lab-project-3008f.appspot.com',
    iosClientId: '690601335117-tptv5saanq3mnod5uc49jifeiq5q59rk.apps.googleusercontent.com',
    iosBundleId: 'com.siddharth.loginRegister',
  );
}
